### ISSUE TITLE
imfuse: improve workflow

### ISSUE THREAD

**Issue by holgerd001** [mviereck/microscopy-tools#12]
> align_image_stack -m -l -C --use-given-order IMAGES

Do you know what "linear input files" (-l) are?
I additionally use -c<num of CPs>. E.g. c60. Afaik the default is 8.

------
(Edit by @mviereck: discussed wiki page: https://github.com/mviereck/microscopy-tools/wiki/imfuse:-Workflow-to-find-good-parameter-sets )

**Comment by mviereck** [comment]
> Do you know what "linear input files" (-l) are?

In fact I don't. Likely this option is useless here, I've removed it from the wiki page.
Here I find a hint that it might mean some sort of linear color space: https://pulsar124.fandom.com/wiki/Open_Source_workflow_for_macro_focus_stacking

>  I additionally use -c. E.g. c60. Afaik the default is 8.

That likely costs time. Do you see an obvious improvement with more control points?

**Comment by holgerd001** [comment]
> I find a hint that it might mean some sort of linear color space

Now I found this: `First we need to know what linear color space is. Simply, it means that numerical intensity values correspond proportionally to their perceived intensity. This means that the colors can be added and multiplied correctly.` at https://www.kinematicsoup.com/news/2016/6/15/gamma-and-linear-space-what-they-are-how-they-differ.

**Comment by holgerd001** [comment]
> That likely costs time. Do you see an obvious improvement with more control points?

Yes, in general: more CPs means better alignment. But you are right, it costs time. So if the default does not lead to exact aligned images, it's reasonable to use -c. In my experiences sometimes there are aligned images in the stack which are **not** really well aligned. Before I use imfuse I check every image of the stack.
Some hints for align_image_stack are here: https://photo.stackexchange.com/questions/83178/cannot-align-images-with-align-image-stack.

**Comment by mviereck** [comment]
> Now I found this

I still have a bit trouble to understand the consequences. On the one hand, I'd assume that this is part of the image and its metadata, so we should not need to care about this.
On the other hand, this might have consequences for image handling of imfuse. I'll have to study this text.

> Yes, in general: more CPs means better alignment. But you are right, it costs time.

I've added this and the link to the wiki page.

**Comment by holgerd001** [comment]
An other hint for the workflow:

To save time in the process of finding the best parameters and arguments it helps to decrease the amount of data. One method is to shrink the images e.g. down to 20%. But many parameters use a radius and/or sigma. And the effect of them depends on the number of pixels around a core. So the result would differ between a shrunken and a original image.
So it can be a good method to select a significant section of the original images and extract this to a separate stack of cropped images.

1. determine existing offset
The aligned stack of images may have an offset. These offset occurs if `align_image_stack` is used with the parameter -C (crop). This is reasonable, but can lead into an offset.
`identify` can show these offset (and many other attributes).
Example:
`~> identify aligned_C_c60_m_000?.tif`
`aligned_C_c60_m_0000.tif TIFF 3897x2595 3897x2595+348+243 8-bit sRGB 24.3508MiB 0.000u 0:00.000
aligned_C_c60_m_0001.tif TIFF 3897x2595 3897x2595+348+243 8-bit sRGB 25.307MiB 0.000u 0:00.000
aligned_C_c60_m_0002.tif TIFF 3897x2595 3897x2595+348+243 8-bit sRGB 25.3951MiB 0.000u 0:00.000`

The three images have the dimensions 3897x2595 pixels and an offset of +348+243.

2. determine the clipping
Open one of the aligned images with a image viewer (e.g. gwenview). 
Choose a significant section.
Note the dimensions and the offset.
E.g. 1500x2200+587+254

3. calculate the total offset
Add both offsets for each direction.
E.g. 
348+587 = 935
243+254 = 497

4. generate the cropped images
Imagemagick provide the command `convert` with the argument -crop to do so.
And to crop all images of the stack the for-loop is used.
 
`~> for i in alig*.tif; do convert $i -crop 1500x2200+935+497  croped_$i; done`

**Comment by mviereck** [comment]
Thanks for this guidance. It is a bit too much for the workflow page yet, but for now I've added a link to your post in the wiki.
