### ISSUE TITLE
imfuse: magick: unable to open image

### ISSUE THREAD

**Issue by holgerd001** [mviereck/microscopy-tools#13]
Hi,
I'm back again. Unfortunately with an error:

`magick: unable to open image '/mnt/Daten/holger/Fotos/stacks/20210417_Ameise3_4_Mikroskopobjektiv_nonplan/byrawtherapee/cache.imfuse/soft-levelU_diffstat.d517e4.tif': Datei oder Verzeichnis nicht gefunden @ error/blob.c/OpenBlob/3537.`

I started imfuse with: `imfuse --soft --diffstat  aligned_C_c16_corr08_g11_m_order_00??.tif -v --cache`

After 9 minutes I got the error message above. The error is reproducible.

Sorry for being absent for that long time. But, as you see, I'm using imfuse again.

Greetings, Holger

**Comment by mviereck** [comment]
Hi,

nice to read you again!
I've uploaded a recent version that works here. I did several changes in the meantime without uploading them, so I currently don't know what the origin bug was in your case. But should work now.

Option `--soft` is experimental yet, I hope I can improve the results. It is an attempt to reproduce the concept of enfuse.

Greetings, Martin

**Comment by holgerd001** [comment]
I just loaded imfuse 0.6.10 down. Separately because the zip-file contains still the old version. And got the same error again. 
...
imfuse: Focus soft 60/60. Duration: 00:07:12; ETA: 00:00:00
imfuse: histogram:
/mnt/Daten/holger/Fotos/stacks/20210417_Ameise3_4_Mikroskopobjektiv_nonplan/byrawtherapee/cache0610/soft-levelU_diffstat.bbdc91.addmask.tif.histogram-uniform.tif
magick: unable to open image '/mnt/Daten/holger/Fotos/stacks/20210417_Ameise3_4_Mikroskopobjektiv_nonplan/byrawtherapee/cache0610/soft-levelU_diffstat.bbdc91.tif': Datei oder Verzeichnis nicht gefunden @ error/blob.c/OpenBlob/3537.
imfuse note: Ready after 00:09:48

Without --soft it works.

**Comment by mviereck** [comment]
Ok, now I found and fixed the bug: it only happened if running without `-V`, but I always did. I tried to save some calculation time for intermediate results, but at least the final result must be generated.

**Comment by holgerd001** [comment]
Ok, now it works.
