### ISSUE TITLE
Beginner guide for dummies?

### ISSUE THREAD

**Issue by LGimmick** [mviereck/microscopy-tools#16]
Hi,
[EN]
I want to try imfuse, but tbh: I don't know where to start. Can I use your scripts with the portable imagemagick (never used before) version? 
May it be possible to get a beginner guide, that explaines the workflow step by step? My first tests resulted in never ending messages, that told me basically I did everything wrong ;)

[Ger]
Ich würde gerne imfuse ausprobieren, habe aber ehrlich gesagt nicht verstanden, was ich wie genau machen muss. Ich habe hier die portable Version von Imagemagick, aber wo trage ich die Pfade dazu jetzt ein, oder muss ich alles zusammen kopieren? Gäbe es die Möglichkeit eine kurze Schritt-für-schritt-Anleitung in das Wiki einzutragen?
Die ersten Versuche ergaben nur eine nicht endende Terminal-Ausgabe, die mir gesagt hat, dass ich eigentlich alles falsch gemacht habe :D 

Danke :)

**Comment by mviereck** [comment]
Hallo,

danke, daß Du imfuse ausprobieren willst!
Ein "beginners guide" ist hier: https://github.com/mviereck/microscopy-tools/wiki/imfuse:-Workflow-to-find-good-parameter-sets
Die Anleitung ist schon etwas alt, ich bin nicht sicher, ob das alles noch aktuell ist. Aber probier es mal aus.
Frag gern weiter, wenn es Probleme gibt.

Die portable Version von Imagemagick kannst Du am Besten nach `/usr/local/bin` kopieren, da wird imfuse es finden. Achte nur darauf, daß sie als ausführbar markiert ist (`sudo chmod +x /usr/local/bin/magick`).

**Comment by LGimmick** [comment]
Mein Versäumnis: Nutze Windows 10/11. Und führe das Script über die Eingabeaufforderung aus.

**Comment by mviereck** [comment]
Ah, ok. Das ist etwas spezieller, sollte aber prinzipiell möglich sein.
Windows cmd.exe oder powershell werden nicht funktionieren.

Hat Dein Windows WSL oder WSL2?
Falls nicht, geht wahrscheinlich auch Cygwin.

Hast Du Grunderfahrung mit Linux?

Ich hoffe mal, Dein Windows hat WSL oder WSL2. 
 - In WSL Ubuntu oder Debian installieren. 
 - Darin dann `imfuse` und `magick` nach `/usr/local/bin`.  imagemagick muß dann die [Linux-Version](https://download.imagemagick.org/ImageMagick/download/binaries/magick) sein. (Falls die in WSL nicht funktioniert, dann installiere stattdessen mit `sudo apt install imagemagick`, ist dann nur eine ältere Version.)
 - Beide ausführbar machen. `chmod +x /usr/local/bin/imfuse /usr/local/bin/magick`
 - Die Windows-Dateien (und Deine Bilder) müßten unter `/mnt/c/ ...` zu finden sein.

**Comment by LGimmick** [comment]
Ok, danke. Hatte ich nicht verstanden, dass das nur unter Linux geht.
Hab's auf einem Linux-Zweitsystem mit installiertem Imagemagick und enfuse probiert -> geht sofort ohne Probleme. Das Ergebnis fand ich auch überzeugend.

Schade, dass es direkt unter Win nicht möglich ist ;)

**Comment by mviereck** [comment]
Ich bin dabei, ein paar Wikiseiten mit Erklärungen und Beispielen zu schreiben: https://github.com/mviereck/microscopy-tools/wiki

Vielleicht hast Du ja Interesse, noch mal ein wenig auzuprobieren.

Prinzipiell sollte das auch unter Windows in WSL laufen können.
