### ISSUE TITLE
imfuse: exif meta data transfer

### ISSUE THREAD

**Issue by mviereck** [mviereck/microscopy-tools#5]
imfuse provides a new option `--exif [=IMAGE]` for exif meta data transfer to the result.

Instead of always transferring the exif data from the first input image as discussed and developed in #2, it is now needed to specify option `--exif` explicitly for this behaviour.

Optionally it is possible to provide an image name as argument; if given, the exif meta data from that image will be transferred.

The `Orientation` tag is removed because it can cause issues in image processing.

**Comment by holgerd001** [comment]
> imfuse provides a new option `--exif [=IMAGE]` for exif meta data transfer to the result.

It doesn't work like I expected, but perhaps like you do. :-)

That's what I've done:
imfuse -o imfu_log_satw3_pc20.tif --log --saturation=w3 --exif D2040938.JPG pc20-aligned_c80_C_m_order_00??.tif

where pc20-aligned_c80_C_m_order_00??.tif are the resized images (20%) and D2040938.JPG is one of the original images out of the camera.
I got an image in the dimensions of D2040938.JPG (4.608x3.072 px), but only a small part contains the picture (697x463). Ok, perhaps is is not a good idea to combine these different files in one command.

**Comment by mviereck** [comment]
> It doesn't work like I expected, but perhaps like you do. :-)
> I got an image in the dimensions of D2040938.JPG (4.608x3.072 px), but only a small part contains the picture (697x463).

Uh, that is not intended. It seems some image size meta data is transferred, and your image viewer displays this size instead of the real one. Which image viewer do you use? geeqie and viewnior show the image in the real pixel size.

Likely the image size meta data must be fixed.

<s>Maybe you could test some possible fixes? Does this fix this?
```
exiftool -overwrite_original -tagsfromfile D2040938.JPG -exifimagewidth= -exifimageheight= -all:all  imfu_log_satw3_pc20.tif
```
</s>
Edit: Nevermind, I'm working on a cleaner solution yet.

**Comment by mviereck** [comment]
I've changed the exif data transfer; all image size information should be excluded now.
I hope the issue is fixed.

**Comment by holgerd001** [comment]
> I've changed the exif data transfer; all image size information should be excluded now.

Hm, I'm not sure, if it's necessary.
I have written a short script to start enfuse and one to start align_image_stack. Only to make it simpler to handle the command line. Especially the --use-given-order parameter was the reason to do so.
Anyway in these script there is a line to transfer the exif data:
`exiftool -overwrite_original -tagsfromfile ${prefix[0]} -all:all x"$outfile2""$outfile1""${name[0]}""${name[1]}""${name[2]}""${name[3]}""${name[4]}""${name[5]}""${name[6]}""${name[7]}""${name[8]}".jpg`
Or more readable: `exiftool -overwrite_original -tagsfromfile <JPG-file> -all:all <by enfuse generated file>`
This works too with different dimensions of `<JPG-file>` and `<by enfuse generated file>`.
I use exiftool version 10.80.


[imfu_log_satw3_pc20_exif.zip](https://github.com/mviereck/microscopy-tools/files/5938494/imfu_log_satw3_pc20_exif.zip)

**Comment by mviereck** [comment]
>  Or more readable: exiftool -overwrite_original -tagsfromfile <JPG-file> -all:all <by enfuse generated file>

This is what I did before, I took your code from a previous example in #2 . Although the images where displayed correctly, I found meta data with the original size. So I assume the root issue is there.

>  I use exiftool version 10.80.

I have exiftool 12.12

> imfu_log_satw3_pc20_exif.zip

Your example is shown here too big, too.

**Comment by holgerd001** [comment]
> I have exiftool 12.12

I checked my repositories, but I found only V 10.80.
Perhaps I make an update manually. But this breaks the consistency of my system.

**Comment by mviereck** [comment]
>  Perhaps I make an update manually. But this breaks the consistency of my system.

This should not be needed. I think the current solution in imfuse that does not transfer any size information should be fine.

Just uploaded another fix: exiftool did not verwrite the target file, nut made a backup. Now no backup is generated.

**Comment by mviereck** [comment]
If you are interested: the current transfer function:
```

exiftransfer() {
  # Transfer exif data from image $1 to image $2
  # Does not transfer image size information.
  # Sets orientation tag to horizontal / no rotation.
  # Several warnings are supressed.
  local Sourceimage Destinationimage Exifargs
  
  Sourceimage="${1:-}"
  Destinationimage="${2:-}"
  Exifargs="$(exiftool -a -u -g1 -args "$Sourceimage")"
  Exifargs="$(LC_ALL=C grep -v -E -- \
    '-ExifTool|-System:|-File:|ImageWidth|ImageHeight|ImageSize|Compression|Orientation|Resolution' <<< "$Exifargs" \
    | sed "s/'/'\"'\"'/g ; s/=/='/ ; s/\$/'/" )"
  eval exiftool -ignoreMinorErrors -overwrite_original_in_place $Exifargs -Orientation=Horizontal "$Destinationimage" 2>&1 | grep -v -E 'Warning|files updated'
}
```
