### ISSUE TITLE
imfuse: Error while flattening images

### ISSUE THREAD

**Issue by holgerd001** [mviereck/microscopy-tools#6]
Idea:
Making many fused images with different parameters.

Preconditions:
- set of aligned and resized photos (here pc20-aligned_c80_C_m_order_00??.tif)
- imfuse v0.6.4.0-beta

Starting imfuse:
`~> imfuse --verbose --diffstat=r3,mean pc20-aligned_c80_C_m_order_00??.tif`

Response:
imfuse note: Setting --output=/mnt/Daten/holger/Fotos/stacks/20210204_Fliege_Kopf_Mikroskopobj/imfuse.diffstat=r3-mean-mean_bg=mean.eb7c3e.tif
...
[Error while flattening images_20210208.zip](https://github.com/mviereck/microscopy-tools/files/5941940/Error.while.flattening.images_20210208.zip)
...
magick: insufficient image data in file `/mnt/Daten/holger/Fotos/stacks/20210204_Fliege_Kopf_Mikroskopobj/cache.imfuse/montage-diffstat.2dc748.tif' @ error/tiff.c/ReadTIFFImage/1774.
imfuse ERROR: Error while flattening images

hints:
That works:
imfuse --verbose --diffstat=r3,max pc20-aligned_c80_C_m_order_00??.tif
imfuse --verbose --diffstat=r3,grad pc20-aligned_c80_C_m_order_00??.tif

**Comment by mviereck** [comment]
Oh no, the same bug again as in #3.
And again, I cannot reproduce it.

Could you please run with `--cache` and provide me the image from the error message?  `/mnt/Daten/holger/Fotos/stacks/20210204_Fliege_Kopf_Mikroskopobj/cache.imfuse/montage-diffstat.2dc748.tif`

I've uploaded a new commit with yet another code for transparent image generation. Though, I doubt that it will really make a difference.

Meanwhile I assume this is a bug in your imagemagick version.
Maybe you could uninstall your repository version and use a static build instead?
The first download entry `magick` is the one I use: https://imagemagick.org/script/download.php

btw, `--diffstat=mean` won't give useable results. This option compares two statistic masks, and results here in comparing two identical mean results. `--diffstat=min,max` is an interesting setup.

In general, could you provide log output at www.pastebin.com? That makes it easier to access and read.

**Comment by holgerd001** [comment]
> btw, --diffstat=mean won't give useable results.
I assumed so, but I did what is possible.

> Could you please run with `--cache`

I have updated magick: Version: ImageMagick 7.0.10-53 Q16 x86_64 20201224
I know that's not the last version, but this was possible on the fly.

1. Versions 
    - imfuse v0.6.4.1-beta
    - ImageMagick 7.0.10-53 Q16 x86_64 20201224

2. Starting imfuse
`> imfuse --verbose --diffstat=r3,mean pc20-aligned_c80_C_m_order_00??.tif`
It works. No errors, no warnings.
That' it.

**Comment by mviereck** [comment]
> It works. No errors, no warnings.
That' it.

Thank you, so it was quite likely an imagemagick bug.
