### ISSUE TITLE
imfuse: cachfile remaining

### ISSUE THREAD

**Issue by holgerd001** [mviereck/microscopy-tools#7]
After `> imfuse --verbose --background=saturation pc20-aligned_c80_C_m_order_00??.tif`
imfuse.bg=saturation.a9a27d.tif was generated.
And a cache file was remaining in the same directory:
cache.imfuseimfuse.saturation_bg=mean.d43748.tif

imfuse v0.6.4.0-beta

**Comment by mviereck** [comment]
Thank you for the report!
Is fixed now. imfuse runs itself with option `--basename` to generate a saturation image, and this option had a parsing bug.

**Comment by holgerd001** [comment]
> Is fixed now. ...

Yes, I can't reproduce it.
