### ISSUE TITLE
mask file remaining

### ISSUE THREAD

**Issue by holgerd001** [mviereck/microscopy-tools#8]
After `imfuse --dog=s0.3 --finalblur=w10,s1 --less=6 --cutblur=0.5` imfuse.dog=s0.3-s0.48_less6_cutblur0.5_finalblur=w10-s1.2783bf.tif was generated.
And a mask file was remaining in the same directory: fb_maskmax.tif

Versions: 
imfuse v0.6.4.1-beta
ImageMagick 7.0.10-53

The issue is reproducible.

**Comment by mviereck** [comment]
>  And a mask file was remaining in the same directory: fb_maskmax.tif

ups, indeed. Is fixed now, thanks!
